import CartProvider from "@/providers/CartProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "./components/footer/Footer";
import Navbar from "./components/nav/Navbar";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["700", "200", "400"] });

export const metadata: Metadata = {
  title: "e-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
