import { getCurrentUser } from "@/actions/getCurrentUser";
import CartProvider from "@/providers/CartProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./components/footer/Footer";
import Navbar from "./components/nav/Navbar";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["700", "200", "400"] });

export const metadata: Metadata = {
  title: "e-shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  console.log("USername: ", currentUser);

  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <Toaster
          toastOptions={{
            style: {
              background: "rgb(51 65 85)",
              color: "#fff",
            },
          }}
        />
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
